default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: hariom

development:
  <<: *default
  database: incyde_development

test:
  <<: *default
  database: incyde_test

production:
  <<: *default
  database: incyde_production
  username: incyde
  password: <%= ENV['INCYDE_NEW_DATABASE_PASSWORD'] %>
