Sector.create(name: "A.- AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA")
Sector.create(name: "0111.- Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas")
Sector.create(name: "0112.- Cultivo de arroz")
Sector.create(name: "0113.- Cultivo de hortalizas, raíces y tubérculos")
Sector.create(name: "0114.- Cultivo de caña de azúcar")
Sector.create(name: "0115.- Cultivo de tabaco")
Sector.create(name: "0116.- Cultivo de plantas para fibras textiles")
Sector.create(name: "0119.- Otros cultivos no perennes")
Sector.create(name: "0121.- Cultivo de la vid")
Sector.create(name: "0122.- Cultivo de frutos tropicales y subtropicales")
Sector.create(name: "0123.- Cultivo de cítricos")
Sector.create(name: "0124.- Cultivo de frutos con hueso y pepitas")
Sector.create(name: "0125.- Cultivo de otros árboles y arbustos frutales y frutos secos")
Sector.create(name: "0126.- Cultivo de frutos oleaginosos")
Sector.create(name: "0127.- Cultivo de plantas para bebidas")
Sector.create(name: "0128.- Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas")
Sector.create(name: "0129.- Otros cultivos perennes")
Sector.create(name: "0130.- Propagación de plantas")
Sector.create(name: "0141.- Explotación de ganado bovino para la producción de leche")
Sector.create(name: "0142.- Explotación de otro ganado bovino y búfalos")
Sector.create(name: "0143.- Explotación de caballos y otros equinos")
Sector.create(name: "0144.- Explotación de camellos y otros camélidos")
Sector.create(name: "0145.- Explotación de ganado ovino y caprino")
Sector.create(name: "0146.- Explotación de ganado porcino")
Sector.create(name: "0147.- Avicultura")
Sector.create(name: "0149.- Otras explotaciones de ganado")
Sector.create(name: "0150.- Producción agrícola combinada con la producción ganadera")
Sector.create(name: "0161.- Actividades de apoyo a la agricultura")
Sector.create(name: "0162.- Actividades de apoyo a la ganadería")
Sector.create(name: "0163.- Actividades de preparación posterior a la cosecha")
Sector.create(name: "0164.- Tratamiento de semillas para reproducción")
Sector.create(name: "0170.- Caza, captura de animales y servicios relacionados con las mismas")
Sector.create(name: "0210.- Silvicultura y otras actividades forestales")
Sector.create(name: "0220.- Explotación de la madera")
Sector.create(name: "0230.- Recolección de productos silvestres, excepto madera")
Sector.create(name: "0240.- Servicios de apoyo a la silvicultura")
Sector.create(name: "0311.- Pesca marina")
Sector.create(name: "0312.- Pesca en agua dulce")
Sector.create(name: "0321.- Acuicultura marina")
Sector.create(name: "0322.- Acuicultura en agua dulce")
Sector.create(name: "B.- INDUSTRIAS EXTRACTIVAS")
Sector.create(name: "0510.- Extracción de antracita y hulla")
Sector.create(name: "0520.- Extracción de lignito")
Sector.create(name: "0610.- Extracción de crudo de petróleo")
Sector.create(name: "0620.- Extracción de gas natural")
Sector.create(name: "0710.- Extracción de minerales de hierro")
Sector.create(name: "0721.- Extracción de minerales de uranio y torio")
Sector.create(name: "0729.- Extracción de otros minerales metálicos no férreos")
Sector.create(name: "0811.- Extracción de piedra ornamental y para la construcción, piedra caliza, yeso, creta y pizarra")
Sector.create(name: "0812.- Extracción de gravas y arenas; extracción de arcilla y caolín")
Sector.create(name: "0891.- Extracción de minerales para productos químicos y fertilizantes")
Sector.create(name: "0892.- Extracción de turba")
Sector.create(name: "0893.- Extracción de sal")
Sector.create(name: "0899.- Otras industrias extractivas n.c.o.p.")
Sector.create(name: "0910.- Actividades de apoyo a la extracción de petróleo y gas natural")
Sector.create(name: "0990.- Actividades de apoyo a otras industrias extractivas")
Sector.create(name: "C.- INDUSTRIA MANUFACTURERA")
Sector.create(name: "1011.- Procesado y conservación de carne")
Sector.create(name: "1012.- Procesado y conservación de volatería")
Sector.create(name: "1013.- Elaboración de productos cárnicos y de volatería")
Sector.create(name: "1021.- Procesado de pescados, crustáceos y moluscos")
Sector.create(name: "1022.- Fabricación de conservas de pescado")
Sector.create(name: "1031.- Procesado y conservación de patatas")
Sector.create(name: "1032.- Elaboración de zumos de frutas y hortalizas")
Sector.create(name: "1039.- Otro procesado y conservación de frutas y hortalizas")
Sector.create(name: "1042.- Fabricación de margarina y grasas comestibles similares")
Sector.create(name: "1043.- Fabricación de aceite de oliva")
Sector.create(name: "1044.- Fabricación de otros aceites y grasas")
Sector.create(name: "1052.- Elaboración de helados")
Sector.create(name: "1053.- Fabricación de quesos")
Sector.create(name: "1054.- Preparación de leche y otros productos lácteos")
Sector.create(name: "1061.- Fabricación de productos de molinería")
Sector.create(name: "1062.- Fabricación de almidones y productos amiláceos")
Sector.create(name: "1071.- Fabricación de pan y de productos frescos de panadería y pastelería")
Sector.create(name: "1072.- Fabricación de galletas y productos de panadería y pastelería de larga duración")
Sector.create(name: "1073.- Fabricación de pastas alimenticias, cuscús y productos similares")
Sector.create(name: "1081.- Fabricación de azúcar")
Sector.create(name: "1082.- Fabricación de cacao, chocolate y productos de confitería")
Sector.create(name: "1083.- Elaboración de café, té e infusiones")
Sector.create(name: "1084.- Elaboración de especias, salsas y condimentos")
Sector.create(name: "1085.- Elaboración de platos y comidas preparados")
Sector.create(name: "1086.- Elaboración de preparados alimenticios homogeneizados y alimentos dietéticos")
Sector.create(name: "1089.- Elaboración de otros productos alimenticios n.c.o.p.")
Sector.create(name: "1091.- Fabricación de productos para la alimentación de animales de granja")
Sector.create(name: "1092.- Fabricación de productos para la alimentación de animales de compañía")
Sector.create(name: "1101.- Destilación, rectificación y mezcla de bebidas alcohólicas")
Sector.create(name: "1102.- Elaboración de vinos")
Sector.create(name: "1103.- Elaboración de sidra y otras bebidas fermentadas a partir de frutas")
Sector.create(name: "1104.- Elaboración de otras bebidas no destiladas, procedentes de la fermentación")
Sector.create(name: "1105.- Fabricación de cerveza")
Sector.create(name: "1106.- Fabricación de malta")
Sector.create(name: "1107.- Fabricación de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas")
Sector.create(name: "1200.- Industria del tabaco")
Sector.create(name: "1310.- Preparación e hilado de fibras textiles")
Sector.create(name: "1320.- Fabricación de tejidos textiles")
Sector.create(name: "1330.- Acabado de textiles")
Sector.create(name: "1391.- Fabricación de tejidos de punto")
Sector.create(name: "1392.- Fabricación de artículos confeccionados con textiles, excepto prendas de vestir")
Sector.create(name: "1393.- Fabricación de alfombras y moquetas")
Sector.create(name: "1394.- Fabricación de cuerdas, cordeles, bramantes y redes")
Sector.create(name: "1395.- Fabricación de telas no tejidas y artículos confeccionados con ellas, excepto prendas de vestir")
Sector.create(name: "1396.- Fabricación de otros productos textiles de uso técnico e industrial")
Sector.create(name: "1399.- Fabricación de otros productos textiles n.c.o.p.")
Sector.create(name: "1411.- Confección de prendas de vestir de cuero")
Sector.create(name: "1412.- Confección de ropa de trabajo")
Sector.create(name: "1413.- Confección de otras prendas de vestir exteriores")
Sector.create(name: "1414.- Confección de ropa interior")
Sector.create(name: "1419.- Confección de otras prendas de vestir y accesorios")
Sector.create(name: "1420.- Fabricación de artículos de peletería")
Sector.create(name: "1431.- Confección de calcetería")
Sector.create(name: "1439.- Confección de otras prendas de vestir de punto")
Sector.create(name: "1511.- Preparación, curtido y acabado del cuero; preparación y teñido de pieles")
Sector.create(name: "1512.- Fabricación de artículos de marroquinería, viaje y de guarnicionería y talabartería")
Sector.create(name: "1520.- Fabricación de calzado")
Sector.create(name: "1610.- Aserrado y cepillado de la madera")
Sector.create(name: "1621.- Fabricación de chapas y tableros de madera")
Sector.create(name: "1622.- Fabricación de suelos de madera ensamblados")
Sector.create(name: "1623.- Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción")
Sector.create(name: "1624.- Fabricación de envases y embalajes de madera")
Sector.create(name: "1629.- Fabricación de otros productos de madera; artículos de corcho, cestería y espartería")
Sector.create(name: "1711.- Fabricación de pasta papelera")
Sector.create(name: "1712.- Fabricación de papel y cartón")
Sector.create(name: "1721.- Fabricación de papel y cartón ondulados; fabricación de envases y embalajes de papel y cartón")
Sector.create(name: "1722.- Fabricación de artículos de papel y cartón para uso doméstico, sanitario e higiénico")
Sector.create(name: "1723.- Fabricación de artículos de papelería")
Sector.create(name: "1724.- Fabricación de papeles pintados")
Sector.create(name: "1729.- Fabricación de otros artículos de papel y cartón")
Sector.create(name: "1811.- Artes gráficas y servicios relacionados con las mismas")
Sector.create(name: "1812.- Otras actividades de impresión y artes gráficas")
Sector.create(name: "1813.- Servicios de preimpresión y preparación de soportes")
Sector.create(name: "1814.- Encuadernación y servicios relacionados con la misma")
Sector.create(name: "1820.- Reproducción de soportes grabados")
Sector.create(name: "1910.- Coquerías")
Sector.create(name: "1920.- Refino de petróleo")
Sector.create(name: "2011.- Fabricación de gases industriales")
Sector.create(name: "2012.- Fabricación de colorantes y pigmentos")
Sector.create(name: "2013.- Fabricación de otros productos básicos de química inorgánica")
Sector.create(name: "2014.- Fabricación de otros productos básicos de química orgánica")
Sector.create(name: "2015.- Fabricación de fertilizantes y compuestos nitrogenados")
Sector.create(name: "2016.- Fabricación de plásticos en formas primarias")
Sector.create(name: "2017.- Fabricación de caucho sintético en formas primarias")
Sector.create(name: "2020.- Fabricación de pesticidas y otros productos agroquímicos")
Sector.create(name: "2030.- Fabricación de pinturas, barnices y revestimientos similares; tintas de imprenta y masillas")
Sector.create(name: "2041.- Fabricación de jabones, detergentes y otros artículos de limpieza y abrillantamiento")
Sector.create(name: "2042.- Fabricación de perfumes y cosméticos")
Sector.create(name: "2051.- Fabricación de explosivos")
Sector.create(name: "2052.- Fabricación de colas")
Sector.create(name: "2053.- Fabricación de aceites esenciales")
Sector.create(name: "2059.- Fabricación de otros productos químicos n.c.o.p.")
Sector.create(name: "2060.- Fabricación de fibras artificiales y sintéticas")
Sector.create(name: "2110.- Fabricación de productos farmacéuticos de base")
Sector.create(name: "2120.- Fabricación de especialidades farmacéuticas")
Sector.create(name: "2211.- Fabricación de neumáticos y cámaras de caucho; reconstrucción y recauchutado de neumáticos")
Sector.create(name: "2219.- Fabricación de otros productos de caucho")
Sector.create(name: "2221.- Fabricación de placas, hojas, tubos y perfiles de plástico")
Sector.create(name: "2222.- Fabricación de envases y embalajes de plástico")
Sector.create(name: "2223.- Fabricación de productos de plástico para la construcción")
Sector.create(name: "2229.- Fabricación de otros productos de plástico")
Sector.create(name: "2311.- Fabricación de vidrio plano")
Sector.create(name: "2312.- Manipulado y transformación de vidrio plano")
Sector.create(name: "2313.- Fabricación de vidrio hueco")
Sector.create(name: "2314.- Fabricación de fibra de vidrio")
Sector.create(name: "2319.- Fabricación y manipulado de otro vidrio, incluido el vidrio técnico")
Sector.create(name: "2320.- Fabricación de productos cerámicos refractarios")
Sector.create(name: "2331.- Fabricación de azulejos y baldosas de cerámica")
Sector.create(name: "2332.- Fabricación de ladrillos, tejas y productos de tierras cocidas para la construcción")
Sector.create(name: "2341.- Fabricación de artículos cerámicos de uso doméstico y ornamental")
Sector.create(name: "2342.- Fabricación de aparatos sanitarios cerámicos")
Sector.create(name: "2343.- Fabricación de aisladores y piezas aislantes de material cerámico")
Sector.create(name: "2344.- Fabricación de otros productos cerámicos de uso técnico")
Sector.create(name: "2349.- Fabricación de otros productos cerámicos")
Sector.create(name: "2351.- Fabricación de cemento")
Sector.create(name: "2352.- Fabricación de cal y yeso")
Sector.create(name: "2361.- Fabricación de elementos de hormigón para la construcción")
Sector.create(name: "2362.- Fabricación de elementos de yeso para la construcción")
Sector.create(name: "2363.- Fabricación de hormigón fresco")
Sector.create(name: "2364.- Fabricación de mortero")
Sector.create(name: "2365.- Fabricación de fibrocemento")
Sector.create(name: "2369.- Fabricación de otros productos de hormigón, yeso y cemento")
Sector.create(name: "2370.- Corte, tallado y acabado de la piedra")
Sector.create(name: "2391.- Fabricación de productos abrasivos")
Sector.create(name: "2399.- Fabricación de otros productos minerales no metálicos n.c.o.p.")
Sector.create(name: "2410.- Fabricación de productos básicos de hierro, acero y ferroaleaciones")
Sector.create(name: "2420.- Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de acero")
Sector.create(name: "2431.- Estirado en frío")
Sector.create(name: "2432.- Laminación en frío")
Sector.create(name: "2433.- Producción de perfiles en frío por conformación con plegado")
Sector.create(name: "2434.- Trefilado en frío")
Sector.create(name: "2441.- Producción de metales preciosos")
Sector.create(name: "2442.- Producción de aluminio")
Sector.create(name: "2443.- Producción de plomo, zinc y estaño")
Sector.create(name: "2444.- Producción de cobre")
Sector.create(name: "2445.- Producción de otros metales no férreos")
Sector.create(name: "2446.- Procesamiento de combustibles nucleares")
Sector.create(name: "2451.- Fundición de hierro")
Sector.create(name: "2452.- Fundición de acero")
Sector.create(name: "2453.- Fundición de metales ligeros")
Sector.create(name: "2454.- Fundición de otros metales no férreos")
Sector.create(name: "2511.- Fabricación de estructuras metálicas y sus componentes")
Sector.create(name: "2512.- Fabricación de carpintería metálica")
Sector.create(name: "2521.- Fabricación de radiadores y calderas para calefacción central")
Sector.create(name: "2529.- Fabricación de otras cisternas, grandes depósitos y contenedores de metal")
Sector.create(name: "2530.- Fabricación de generadores de vapor, excepto calderas de calefacción central")
Sector.create(name: "2540.- Fabricación de armas y municiones")
Sector.create(name: "2550.- Forja, estampación y embutición de metales; metalurgia de polvos")
Sector.create(name: "2561.- Tratamiento y revestimiento de metales")
Sector.create(name: "2562.- Ingeniería mecánica por cuenta de terceros")
Sector.create(name: "2571.- Fabricación de artículos de cuchillería y cubertería")
Sector.create(name: "2572.- Fabricación de cerraduras y herrajes")
Sector.create(name: "2573.- Fabricación de herramientas")
Sector.create(name: "2591.- Fabricación de bidones y toneles de hierro o acero")
Sector.create(name: "2592.- Fabricación de envases y embalajes metálicos ligeros")
Sector.create(name: "2593.- Fabricación de productos de alambre, cadenas y muelles")
Sector.create(name: "2594.- Fabricación de pernos y productos de tornillería")
Sector.create(name: "2599.- Fabricación de otros productos metálicos n.c.o.p.")
Sector.create(name: "2611.- Fabricación de componentes electrónicos")
Sector.create(name: "2612.- Fabricación de circuitos impresos ensamblados")
Sector.create(name: "2620.- Fabricación de ordenadores y equipos periféricos")
Sector.create(name: "2630.- Fabricación de equipos de telecomunicaciones")
Sector.create(name: "2640.- Fabricación de productos electrónicos de consumo")
Sector.create(name: "2651.- Fabricación de instrumentos y aparatos de medida, verificación y navegación")
Sector.create(name: "2652.- Fabricación de relojes")
Sector.create(name: "2660.- Fabricación de equipos de radiación, electromédicos y electroterapéuticos")
Sector.create(name: "2670.- Fabricación de instrumentos de óptica y equipo fotográfico")
Sector.create(name: "2680.- Fabricación de soportes magnéticos y ópticos")
Sector.create(name: "2711.- Fabricación de motores, generadores y transformadores eléctricos")
Sector.create(name: "2712.- Fabricación de aparatos de distribución y control eléctrico")
Sector.create(name: "2720.- Fabricación de pilas y acumuladores eléctricos")
Sector.create(name: "2731.- Fabricación de cables de fibra óptica")
Sector.create(name: "2732.- Fabricación de otros hilos y cables electrónicos y eléctricos")
Sector.create(name: "2733.- Fabricación de dispositivos de cableado")
Sector.create(name: "2740.- Fabricación de lámparas y aparatos eléctricos de iluminación")
Sector.create(name: "2751.- Fabricación de electrodomésticos")
Sector.create(name: "2752.- Fabricación de aparatos domésticos no eléctricos")
Sector.create(name: "2790.- Fabricación de otro material y equipo eléctrico")
Sector.create(name: "2811.- Fabricación de motores y turbinas, excepto los destinados a aeronaves, vehículos automóviles y ciclomotores")
Sector.create(name: "2812.- Fabricación de equipos de transmisión hidráulica y neumática")
Sector.create(name: "2813.- Fabricación de otras bombas y compresores")
Sector.create(name: "2814.- Fabricación de otra grifería y válvulas")
Sector.create(name: "2815.- Fabricación de cojinetes, engranajes y órganos mecánicos de transmisión")
Sector.create(name: "2821.- Fabricación de hornos y quemadores")
Sector.create(name: "2822.- Fabricación de maquinaria de elevación y manipulación")
Sector.create(name: "2823.- Fabricación de máquinas y equipos de oficina, excepto equipos informáticos")
Sector.create(name: "2824.- Fabricación de herramientas eléctricas manuales")
Sector.create(name: "2825.- Fabricación de maquinaria de ventilación y refrigeración no doméstica")
Sector.create(name: "2829.- Fabricación de otra maquinaria de uso general n.c.o.p.")
Sector.create(name: "2830.- Fabricación de maquinaria agraria y forestal")
Sector.create(name: "2841.- Fabricación de máquinas herramienta para trabajar el metal")
Sector.create(name: "2849.- Fabricación de otras máquinas herramienta")
Sector.create(name: "2891.- Fabricación de maquinaria para la industria metalúrgica")
Sector.create(name: "2892.- Fabricación de maquinaria para las industrias extractivas y de la construcción")
Sector.create(name: "2893.- Fabricación de maquinaria para la industria de la alimentación, bebidas y tabaco")
Sector.create(name: "2894.- Fabricación de maquinaria para las industrias textil, de la confección y del cuero")
Sector.create(name: "2895.- Fabricación de maquinaria para la industria del papel y del cartón")
Sector.create(name: "2896.- Fabricación de maquinaria para la industria del plástico y el caucho")
Sector.create(name: "2899.- Fabricación de otra maquinaria para usos específicos n.c.o.p.")
Sector.create(name: "2910.- Fabricación de vehículos de motor")
Sector.create(name: "2920.- Fabricación de carrocerías para vehículos de motor; fabricación de remolques y semirremolques")
Sector.create(name: "2931.- Fabricación de equipos eléctricos y electrónicos para vehículos de motor")
Sector.create(name: "2932.- Fabricación de otros componentes, piezas y accesorios para vehículos de motor")
Sector.create(name: "3011.- Construcción de barcos y estructuras flotantes")
Sector.create(name: "3012.- Construcción de embarcaciones de recreo y deporte")
Sector.create(name: "3020.- Fabricación de locomotoras y material ferroviario")
Sector.create(name: "3030.- Construcción aeronáutica y espacial y su maquinaria")
Sector.create(name: "3040.- Fabricación de vehículos militares de combate")
Sector.create(name: "3091.- Fabricación de motocicletas")
Sector.create(name: "3092.- Fabricación de bicicletas y de vehículos para personas con discapacidad")
Sector.create(name: "3099.- Fabricación de otro material de transporte n.c.o.p.")
Sector.create(name: "3101.- Fabricación de muebles de oficina y de establecimientos comerciales")
Sector.create(name: "3102.- Fabricación de muebles de cocina")
Sector.create(name: "3103.- Fabricación de colchones")
Sector.create(name: "3109.- Fabricación de otros muebles")
Sector.create(name: "3211.- Fabricación de monedas")
Sector.create(name: "3212.- Fabricación de artículos de joyería y artículos similares")
Sector.create(name: "3213.- Fabricación de artículos de bisutería y artículos similares")
Sector.create(name: "3220.- Fabricación de instrumentos musicales")
Sector.create(name: "3230.- Fabricación de artículos de deporte")
Sector.create(name: "3240.- Fabricación de juegos y juguetes")
Sector.create(name: "3250.- Fabricación de instrumentos y suministros médicos y odontológicos")
Sector.create(name: "3291.- Fabricación de escobas, brochas y cepillos")
Sector.create(name: "3299.- Otras industrias manufactureras n.c.o.p.")
Sector.create(name: "3311.- Reparación de productos metálicos")
Sector.create(name: "3312.- Reparación de maquinaria")
Sector.create(name: "3313.- Reparación de equipos electrónicos y ópticos")
Sector.create(name: "3314.- Reparación de equipos eléctricos")
Sector.create(name: "3315.- Reparación y mantenimiento naval")
Sector.create(name: "3316.- Reparación y mantenimiento aeronáutico y espacial")
Sector.create(name: "3317.- Reparación y mantenimiento de otro material de transporte")
Sector.create(name: "3319.- Reparación de otros equipos")
Sector.create(name: "3320.- Instalación de máquinas y equipos industriales")
Sector.create(name: "D.- SUMINISTRO DE ENERGÍA ELÉCTRICA, GAS, VAPOR Y AIRE ACONDICIONADO")
Sector.create(name: "3512.- Transporte de energía eléctrica")
Sector.create(name: "3513.- Distribución de energía eléctrica")
Sector.create(name: "3514.- Comercio de energía eléctrica")
Sector.create(name: "3515.- Producción de energía hidroeléctrica")
Sector.create(name: "3516.- Producción de energía eléctrica de origen térmico convencional")
Sector.create(name: "3517.- Producción de energía eléctrica de origen nuclear")
Sector.create(name: "3518.- Producción de energía eléctrica de origen eólico")
Sector.create(name: "3519.- Producción de energía eléctrica de otros tipos")
Sector.create(name: "3521.- Producción de gas")
Sector.create(name: "3522.- Distribución por tubería de combustibles gaseosos")
Sector.create(name: "3523.- Comercio de gas por tubería")
Sector.create(name: "3530.- Suministro de vapor y aire acondicionado")
Sector.create(name: "E.- SUMINISTRO DE AGUA, ACTIVIDADES DE SANEAMIENTO, GESTIÓN DE RESIDUOS Y DESCONTAMINACIÓN")
Sector.create(name: "3600.- Captación, depuración y distribución de agua")
Sector.create(name: "3700.- Recogida y tratamiento de aguas residuales")
Sector.create(name: "3811.- Recogida de residuos no peligrosos")
Sector.create(name: "3812.- Recogida de residuos peligrosos")
Sector.create(name: "3821.- Tratamiento y eliminación de residuos no peligrosos")
Sector.create(name: "3822.- Tratamiento y eliminación de residuos peligrosos")
Sector.create(name: "3831.- Separación y clasificación de materiales")
Sector.create(name: "3832.- Valorización de materiales ya clasificados")
Sector.create(name: "3900.- Actividades de descontaminación y otros servicios de gestión de residuos")
Sector.create(name: "F.- CONSTRUCCIÓN")
Sector.create(name: "4110.- Promoción inmobiliaria")
Sector.create(name: "4121.- Construcción de edificios residenciales")
Sector.create(name: "4122.- Construcción de edificios no residenciales")
Sector.create(name: "4211.- Construcción de carreteras y autopistas")
Sector.create(name: "4212.- Construcción de vías férreas de superficie y subterráneas")
Sector.create(name: "4213.- Construcción de puentes y túneles")
Sector.create(name: "4221.- Construcción de redes para fluidos")
Sector.create(name: "4222.- Construcción de redes eléctricas y de telecomunicaciones")
Sector.create(name: "4291.- Obras hidráulicas")
Sector.create(name: "4299.- Construcción de otros proyectos de ingeniería civil n.c.o.p.")
Sector.create(name: "4311.- Demolición")
Sector.create(name: "4312.- Preparación de terrenos")
Sector.create(name: "4313.- Perforaciones y sondeos")
Sector.create(name: "4321.- Instalaciones eléctricas")
Sector.create(name: "4322.- Fontanería, instalaciones de sistemas de calefacción y aire acondicionado")
Sector.create(name: "4329.- Otras instalaciones en obras de construcción")
Sector.create(name: "4331.- Revocamiento")
Sector.create(name: "4332.- Instalación de carpintería")
Sector.create(name: "4333.- Revestimiento de suelos y paredes")
Sector.create(name: "4334.- Pintura y acristalamiento")
Sector.create(name: "4339.- Otro acabado de edificios")
Sector.create(name: "4391.- Construcción de cubiertas")
Sector.create(name: "4399.- Otras actividades de construcción especializada n.c.o.p.")
Sector.create(name: "G.- COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS DE MOTOR Y MOTOCICLETAS")
Sector.create(name: "4511.- Venta de automóviles y vehículos de motor ligeros")
Sector.create(name: "4519.- Venta de otros vehículos de motor")
Sector.create(name: "4520.- Mantenimiento y reparación de vehículos de motor")
Sector.create(name: "4531.- Comercio al por mayor de repuestos y accesorios de vehículos de motor")
Sector.create(name: "4532.- Comercio al por menor de repuestos y accesorios de vehículos de motor")
Sector.create(name: "4540.- Venta, mantenimiento y reparación de motocicletas y de sus repuestos y accesorios")
Sector.create(name: "4611.- Intermediarios del comercio de materias primas agrarias, animales vivos, materias primas textiles y productos semielaborados")
Sector.create(name: "4612.- Intermediarios del comercio de combustibles, minerales, metales y productos químicos industriales")
Sector.create(name: "4613.- Intermediarios del comercio de la madera y materiales de construcción")
Sector.create(name: "4614.- Intermediarios del comercio de maquinaria, equipo industrial, embarcaciones y aeronaves")
Sector.create(name: "4615.- Intermediarios del comercio de muebles, artículos para el hogar y ferretería")
Sector.create(name: "4616.- Intermediarios del comercio de textiles, prendas de vestir, peletería, calzado y artículos de cuero")
Sector.create(name: "4617.- Intermediarios del comercio de productos alimenticios, bebidas y tabaco")
Sector.create(name: "4618.- Intermediarios del comercio especializados en la venta de otros productos específicos")
Sector.create(name: "4619.- Intermediarios del comercio de productos diversos")
Sector.create(name: "4621.- Comercio al por mayor de cereales, tabaco en rama, simientes y alimentos para animales")
Sector.create(name: "4622.- Comercio al por mayor de flores y plantas")
Sector.create(name: "4623.- Comercio al por mayor de animales vivos")
Sector.create(name: "4624.- Comercio al por mayor de cueros y pieles")
Sector.create(name: "4631.- Comercio al por mayor de frutas y hortalizas")
Sector.create(name: "4632.- Comercio al por mayor de carne y productos cárnicos")
Sector.create(name: "4633.- Comercio al por mayor de productos lácteos, huevos, aceites y grasas comestibles")
Sector.create(name: "4634.- Comercio al por mayor de bebidas")
Sector.create(name: "4635.- Comercio al por mayor de productos del tabaco")
Sector.create(name: "4636.- Comercio al por mayor de azúcar, chocolate y confitería")
Sector.create(name: "4637.- Comercio al por mayor de café, té, cacao y especias")
Sector.create(name: "4638.- Comercio al por mayor de pescados y mariscos y otros productos alimenticios")
Sector.create(name: "4639.- Comercio al por mayor, no especializado, de productos alimenticios, bebidas y tabaco")
Sector.create(name: "4641.- Comercio al por mayor de textiles")
Sector.create(name: "4642.- Comercio al por mayor de prendas de vestir y calzado")
Sector.create(name: "4643.- Comercio al por mayor de aparatos electrodomésticos")
Sector.create(name: "4644.- Comercio al por mayor de porcelana, cristalería y artículos de limpieza")
Sector.create(name: "4645.- Comercio al por mayor de productos perfumería y cosmética")
Sector.create(name: "4646.- Comercio al por mayor de productos farmacéuticos")
Sector.create(name: "4647.- Comercio al por mayor de muebles, alfombras y aparatos de iluminación")
Sector.create(name: "4648.- Comercio al por mayor de artículos de relojería y joyería")
Sector.create(name: "4649.- Comercio al por mayor de otros artículos de uso doméstico")
Sector.create(name: "4651.- Comercio al por mayor de ordenadores, equipos periféricos y programas informáticos")
Sector.create(name: "4652.- Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes")
Sector.create(name: "4661.- Comercio al por mayor de maquinaria, equipos y suministros agrícolas")
Sector.create(name: "4662.- Comercio al por mayor de máquinas herramienta")
Sector.create(name: "4663.- Comercio al por mayor de maquinaria para la minería, la construcción y la ingeniería civil")
Sector.create(name: "4664.- Comercio al por mayor de maquinaria para la industria textil y de máquinas de coser y tricotar")
Sector.create(name: "4665.- Comercio al por mayor de muebles de oficina")
Sector.create(name: "4666.- Comercio al por mayor de otra maquinaria y equipo de oficina")
Sector.create(name: "4669.- Comercio al por mayor de otra maquinaria y equipo")
Sector.create(name: "4671.- Comercio al por mayor de combustibles sólidos, líquidos y gaseosos, y productos similares")
Sector.create(name: "4672.- Comercio al por mayor de metales y minerales metálicos")
Sector.create(name: "4673.- Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios")
Sector.create(name: "4674.- Comercio al por mayor de ferretería, fontanería y calefacción")
Sector.create(name: "4675.- Comercio al por mayor de productos químicos")
Sector.create(name: "4676.- Comercio al por mayor de otros productos semielaborados")
Sector.create(name: "4677.- Comercio al por mayor de chatarra y productos de desecho")
Sector.create(name: "4690.- Comercio al por mayor no especializado")
Sector.create(name: "4711.- Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco")
Sector.create(name: "4719.- Otro comercio al por menor en establecimientos no especializados")
Sector.create(name: "4721.- Comercio al por menor de frutas y hortalizas en establecimientos especializados")
Sector.create(name: "4722.- Comercio al por menor de carne y productos cárnicos en establecimientos especializados")
Sector.create(name: "4723.- Comercio al por menor de pescados y mariscos en establecimientos especializados")
Sector.create(name: "4724.- Comercio al por menor de pan y productos de panadería, confitería y pastelería en establecimientos especializados")
Sector.create(name: "4725.- Comercio al por menor de bebidas en establecimientos especializados")
Sector.create(name: "4726.- Comercio al por menor de productos de tabaco en establecimientos especializados")
Sector.create(name: "4729.- Otro comercio al por menor de productos alimenticios en establecimientos especializados")
Sector.create(name: "4730.- Comercio al por menor de combustible para la automoción en establecimientos especializados")
Sector.create(name: "4741.- Comercio al por menor de ordenadores, equipos periféricos y programas informáticos en establecimientos especializados")
Sector.create(name: "4742.- Comercio al por menor de equipos de telecomunicaciones en establecimientos especializados")
Sector.create(name: "4743.- Comercio al por menor de equipos de audio y vídeo en establecimientos especializados")
Sector.create(name: "4751.- Comercio al por menor de textiles en establecimientos especializados")
Sector.create(name: "4752.- Comercio al por menor de ferretería, pintura y vidrio en establecimientos especializados")
Sector.create(name: "4753.- Comercio al por menor de alfombras, moquetas y revestimientos de paredes y suelos en establecimientos especializados")
Sector.create(name: "4754.- Comercio al por menor de aparatos electrodomésticos en establecimientos especializados")
Sector.create(name: "4759.- Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados")
Sector.create(name: "4761.- Comercio al por menor de libros en establecimientos especializados")
Sector.create(name: "4762.- Comercio al por menor de periódicos y artículos de papelería en establecimientos especializados")
Sector.create(name: "4763.- Comercio al por menor de grabaciones de música y vídeo en establecimientos especializados")
Sector.create(name: "4764.- Comercio al por menor de artículos deportivos en establecimientos especializados")
Sector.create(name: "4765.- Comercio al por menor de juegos y juguetes en establecimientos especializados")
Sector.create(name: "4771.- Comercio al por menor de prendas de vestir en establecimientos especializados")
Sector.create(name: "4772.- Comercio al por menor de calzado y artículos de cuero en establecimientos especializados")
Sector.create(name: "4773.- Comercio al por menor de productos farmacéuticos en establecimientos especializados")
Sector.create(name: "4774.- Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados")
Sector.create(name: "4775.- Comercio al por menor de productos cosméticos e higiénicos en establecimientos especializados")
Sector.create(name: "4776.- Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados")
Sector.create(name: "4777.- Comercio al por menor de artículos de relojería y joyería en establecimientos especializados")
Sector.create(name: "4778.- Otro comercio al por menor de artículos nuevos en establecimientos especializados")
Sector.create(name: "4779.- Comercio al por menor de artículos de segunda mano en establecimientos")
Sector.create(name: "4781.- Comercio al por menor de productos alimenticios, bebidas y tabaco en puestos de venta y en mercadillos")
Sector.create(name: "4782.- Comercio al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y en mercadillos")
Sector.create(name: "4789.- Comercio al por menor de otros productos en puestos de venta y en mercadillos")
Sector.create(name: "4791.- Comercio al por menor por correspondencia o Internet")
Sector.create(name: "4799.- Otro comercio al por menor no realizado ni en establecimientos, ni en puestos de venta ni en mercadillos")
Sector.create(name: "H.- TRANSPORTE Y ALMACENAMIENTO")
Sector.create(name: "4910.- Transporte interurbano de pasajeros por ferrocarril")
Sector.create(name: "4920.- Transporte de mercancías por ferrocarril")
Sector.create(name: "4931.- Transporte terrestre urbano y suburbano de pasajeros")
Sector.create(name: "4932.- Transporte por taxi")
Sector.create(name: "4939.- tipos de transporte terrestre de pasajeros n.c.o.p.")
Sector.create(name: "4941.- Transporte de mercancías por carretera")
Sector.create(name: "4942.- Servicios de mudanza")
Sector.create(name: "4950.- Transporte por tubería")
Sector.create(name: "5010.- Transporte marítimo de pasajeros")
Sector.create(name: "5020.- Transporte marítimo de mercancías")
Sector.create(name: "5030.- Transporte de pasajeros por vías navegables interiores")
Sector.create(name: "5040.- Transporte de mercancías por vías navegables interiores")
Sector.create(name: "5110.- Transporte aéreo de pasajeros")
Sector.create(name: "5121.- Transporte aéreo de mercancías")
Sector.create(name: "5122.- Transporte espacial")
Sector.create(name: "5210.- Depósito y almacenamiento")
Sector.create(name: "5221.- Actividades anexas al transporte terrestre")
Sector.create(name: "5222.- Actividades anexas al transporte marítimo y por vías navegables interiores")
Sector.create(name: "5223.- Actividades anexas al transporte aéreo")
Sector.create(name: "5224.- Manipulación de mercancías")
Sector.create(name: "5229.- Otras actividades anexas al transporte")
Sector.create(name: "5310.- Actividades postales sometidas a la obligación del servicio universal")
Sector.create(name: "5320.- Otras actividades postales y de correos")
Sector.create(name: "I.- HOSTELERÍA")
Sector.create(name: "5510.- Hoteles y alojamientos similares")
Sector.create(name: "5520.- Alojamientos turísticos y otros alojamientos de corta estancia")
Sector.create(name: "5530.- Campings y aparcamientos para caravanas")
Sector.create(name: "5590.- Otros alojamientos")
Sector.create(name: "5610.- Restaurantes y puestos de comidas")
Sector.create(name: "5621.- Provisión de comidas preparadas para eventos")
Sector.create(name: "5629.- Otros servicios de comidas")
Sector.create(name: "5630.- Establecimientos de bebidas")
Sector.create(name: "J.- INFORMACIÓN Y COMUNICACIONES")
Sector.create(name: "5811.- Edición de libros")
Sector.create(name: "5812.- Edición de directorios y guías de direcciones postales")
Sector.create(name: "5813.- Edición de periódicos")
Sector.create(name: "5814.- Edición de revistas")
Sector.create(name: "5819.- Otras actividades editoriales")
Sector.create(name: "5821.- Edición de videojuegos")
Sector.create(name: "5829.- Edición de otros programas informáticos")
Sector.create(name: "5912.- Actividades de postproducción cinematográfica, de vídeo y de programas de televisión")
Sector.create(name: "5914.- Actividades de exhibición cinematográfica")
Sector.create(name: "5915.- Actividades de producción cinematográfica y de vídeo")
Sector.create(name: "5916.- Actividades de producciones de programas de televisión")
Sector.create(name: "5917.- Actividades de distribución cinematográfica y de vídeo")
Sector.create(name: "5918.- Actividades de distribución de programas de televisión")
Sector.create(name: "5920.- Actividades de grabación de sonido y edición musical")
Sector.create(name: "6010.- Actividades de radiodifusión")
Sector.create(name: "6020.- Actividades de programación y emisión de televisión")
Sector.create(name: "6110.- Telecomunicaciones por cable")
Sector.create(name: "6120.- Telecomunicaciones inalámbricas")
Sector.create(name: "6130.- Telecomunicaciones por satélite")
Sector.create(name: "6190.- Otras actividades de telecomunicaciones")
Sector.create(name: "6201.- Actividades de programación informática")
Sector.create(name: "6202.- Actividades de consultoría informática")
Sector.create(name: "6203.- Gestión de recursos informáticos")
Sector.create(name: "6209.- Otros servicios relacionados con las tecnologías de la información y la informática")
Sector.create(name: "6311.- Proceso de datos, hosting y actividades relacionadas")
Sector.create(name: "6312.- Portales web")
Sector.create(name: "6391.- Actividades de las agencias de noticias")
Sector.create(name: "6399.- Otros servicios de información n.c.o.p.")
Sector.create(name: "K.- ACTIVIDADES FINANCIERAS Y DE SEGUROS")
Sector.create(name: "6411.- Banco central")
Sector.create(name: "6419.- Otra intermediación monetaria")
Sector.create(name: "6420.- Actividades de las sociedades holding")
Sector.create(name: "6430.- Inversión colectiva, fondos y entidades financieras similares")
Sector.create(name: "6491.- Arrendamiento financiero")
Sector.create(name: "6492.- Otras actividades crediticias")
Sector.create(name: "6499.- Otros servicios financieros, excepto seguros y fondos de pensiones n.c.o.p.")
Sector.create(name: "6511.- Seguros de vida")
Sector.create(name: "6512.- Seguros distintos de los seguros de vida")
Sector.create(name: "6520.- Reaseguros")
Sector.create(name: "6530.- Fondos de pensiones")
Sector.create(name: "6611.- Administración de mercados financieros")
Sector.create(name: "6612.- Actividades de intermediación en operaciones con valores y otros activos")
Sector.create(name: "6619.- Otras actividades auxiliares a los servicios financieros, excepto seguros y fondos de pensiones")
Sector.create(name: "6621.- Evaluación de riesgos y daños")
Sector.create(name: "6622.- Actividades de agentes y corredores de seguros")
Sector.create(name: "6629.- Otras actividades auxiliares a seguros y fondos de pensiones")
Sector.create(name: "6630.- Actividades de gestión de fondos")
Sector.create(name: "L.- ACTIVIDADES INMOBILIARIAS")
Sector.create(name: "6810.- Compraventa de bienes inmobiliarios por cuenta propia")
Sector.create(name: "6820.- Alquiler de bienes inmobiliarios por cuenta propia")
Sector.create(name: "6831.- Agentes de la propiedad inmobiliaria")
Sector.create(name: "6832.- Gestión y administración de la propiedad inmobiliaria")
Sector.create(name: "M.- ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS")
Sector.create(name: "6910.- Actividades jurídicas")
Sector.create(name: "6920.- Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal")
Sector.create(name: "7010.- Actividades de las sedes centrales")
Sector.create(name: "7021.- Relaciones públicas y comunicación")
Sector.create(name: "7022.- Otras actividades de consultoría de gestión empresarial")
Sector.create(name: "7111.- Servicios técnicos de arquitectura")
Sector.create(name: "7112.- Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico")
Sector.create(name: "7120.- Ensayos y análisis técnicos")
Sector.create(name: "7211.- Investigación y desarrollo experimental en biotecnología")
Sector.create(name: "7219.- Otra investigación y desarrollo experimental en ciencias naturales y técnicas")
Sector.create(name: "7220.- Investigación y desarrollo experimental en ciencias sociales y humanidades")
Sector.create(name: "7311.- Agencias de publicidad")
Sector.create(name: "7312.- Servicios de representación de medios de comunicación")
Sector.create(name: "7320.- Estudio de mercado y realización de encuestas de opinión pública")
Sector.create(name: "7410.- Actividades de diseño especializado")
Sector.create(name: "7420.- Actividades de fotografía")
Sector.create(name: "7430.- Actividades de traducción e interpretación")
Sector.create(name: "7490.- Otras actividades profesionales, científicas y técnicas n.c.o.p.")
Sector.create(name: "7500.- Actividades veterinarias")
Sector.create(name: "N.- ACTIVIDADES ADMINISTRATIVAS Y SERVICIOS AUXLIARES")
Sector.create(name: "7711.- Alquiler de automóviles y vehículos de motor ligeros")
Sector.create(name: "7712.- Alquiler de camiones")
Sector.create(name: "7721.- Alquiler de artículos de ocio y deportivos")
Sector.create(name: "7722.- Alquiler de cintas de vídeo y discos")
Sector.create(name: "7729.- Alquiler de otros efectos personales y artículos de uso doméstico")
Sector.create(name: "7731.- Alquiler de maquinaria y equipo de uso agrícola")
Sector.create(name: "7732.- Alquiler de maquinaria y equipo para la construcción e ingeniería civil")
Sector.create(name: "7733.- Alquiler de maquinaria y equipo de oficina, incluidos ordenadores")
Sector.create(name: "7734.- Alquiler de medios de navegación")
Sector.create(name: "7735.- Alquiler de medios de transporte aéreo")
Sector.create(name: "7739.- Alquiler de otra maquinaria, equipos y bienes tangibles n.c.o.p.")
Sector.create(name: "7740.- Arrendamiento de la propiedad intelectual y productos similares, excepto trabajos protegidos por los derechos de autor")
Sector.create(name: "7810.- Actividades de las agencias de colocación")
Sector.create(name: "7820.- Actividades de las empresas de trabajo temporal")
Sector.create(name: "7830.- Otra provisión de recursos humanos")
Sector.create(name: "7911.- Actividades de las agencias de viajes")
Sector.create(name: "7912.- Actividades de los operadores turísticos")
Sector.create(name: "7990.- Otros servicios de reservas y actividades relacionadas con los mismos")
Sector.create(name: "8010.- Actividades de seguridad privada")
Sector.create(name: "8020.- Servicios de sistemas de seguridad")
Sector.create(name: "8030.- Actividades de investigación")
Sector.create(name: "8110.- Servicios integrales a edificios e instalaciones")
Sector.create(name: "8121.- Limpieza general de edificios")
Sector.create(name: "8122.- Otras actividades de limpieza industrial y de edificios")
Sector.create(name: "8129.- Otras actividades de limpieza")
Sector.create(name: "8130.- Actividades de jardinería")
Sector.create(name: "8211.- Servicios administrativos combinados")
Sector.create(name: "8219.- Actividades de fotocopiado, preparación de documentos y otras actividades especializadas de oficina")
Sector.create(name: "8220.- Actividades de los centros de llamadas")
Sector.create(name: "8230.- Organización de convenciones y ferias de muestras")
Sector.create(name: "8291.- Actividades de las agencias de cobros y de información comercial")
Sector.create(name: "8292.- Actividades de envasado y empaquetado")
Sector.create(name: "8299.- Otras actividades de apoyo a las empresas n.c.o.p.")
Sector.create(name: "O.- ADMINISTRACIÓN PÚBLICA Y DEFENSA; SEGURIDAD SOCIAL OBLIGATORIA")
Sector.create(name: "8411.- Actividades generales de la Administración Pública")
Sector.create(name: "8412.- Regulación de las actividades sanitarias, educativas y culturales y otros servicios sociales, excepto Seguridad Social")
Sector.create(name: "8413.- Regulación de la actividad económica y contribución a su mayor eficiencia")
Sector.create(name: "8421.- Asuntos exteriores")
Sector.create(name: "8422.- Defensa")
Sector.create(name: "8423.- Justicia")
Sector.create(name: "8424.- Orden público y seguridad")
Sector.create(name: "8425.- Protección civil")
Sector.create(name: "8430.- Seguridad Social obligatoria")
Sector.create(name: "P.- EDUCACIÓN")
Sector.create(name: "8510.- Educación preprimaria")
Sector.create(name: "8520.- Educación primaria")
Sector.create(name: "8531.- Educación secundaria general")
Sector.create(name: "8532.- Educación secundaria técnica y profesional")
Sector.create(name: "8541.- Educación postsecundaria no terciaria")
Sector.create(name: "8543.- Educación universitaria")
Sector.create(name: "8544.- Educación terciaria no universitaria")
Sector.create(name: "8551.- Educación deportiva y recreativa")
Sector.create(name: "8552.- Educación cultural")
Sector.create(name: "8553.- Actividades de las escuelas de conducción y pilotaje")
Sector.create(name: "8559.- Otra educación n.c.o.p.")
Sector.create(name: "8560.- Actividades auxiliares a la educación")
Sector.create(name: "Q.- ACTIVIDADES SANITARIAS Y DE SERVICIOS SOCIALES")
Sector.create(name: "8610.- Actividades hospitalarias")
Sector.create(name: "8621.- Actividades de medicina general")
Sector.create(name: "8622.- Actividades de medicina especializada")
Sector.create(name: "8623.- Actividades odontológicas")
Sector.create(name: "8690.- Otras actividades sanitarias")
Sector.create(name: "8710.- Asistencia en establecimientos residenciales con cuidados sanitarios")
Sector.create(name: "8720.- Asistencia en establecimientos residenciales para personas con discapacidad intelectual, enfermedad mental y drogodependencia")
Sector.create(name: "8731.- Asistencia en establecimientos residenciales para personas mayores")
Sector.create(name: "8732.- Asistencia en establecimientos residenciales para personas con discapacidad física")
Sector.create(name: "8790.- Otras actividades de asistencia en establecimientos residenciales")
Sector.create(name: "8811.- Actividades de servicios sociales sin alojamiento para personas mayores")
Sector.create(name: "8812.- Actividades de servicios sociales sin alojamiento para personas con discapacidad")
Sector.create(name: "8891.- Actividades de cuidado diurno de niños")
Sector.create(name: "8899.- Otros actividades de servicios sociales sin alojamiento n.c.o.p.")
Sector.create(name: "R.- ACTIVIDADES ARTÍSTICAS, RECREATIVAS Y DE ENTRENIMIENTO")
Sector.create(name: "9001.- Artes escénicas")
Sector.create(name: "9002.- Actividades auxiliares a las artes escénicas")
Sector.create(name: "9003.- Creación artística y literaria")
Sector.create(name: "9004.- Gestión de salas de espectáculos")
Sector.create(name: "9102.- Actividades de museos")
Sector.create(name: "9103.- Gestión de lugares y edificios históricos")
Sector.create(name: "9104.- Actividades de los jardines botánicos, parques zoológicos y reservas naturales")
Sector.create(name: "9105.- Actividades de bibliotecas")
Sector.create(name: "9106.- Actividades de archivos")
Sector.create(name: "9200.- Actividades de juegos de azar y apuestas")
Sector.create(name: "9311.- Gestión de instalaciones deportivas")
Sector.create(name: "9312.- Actividades de los clubes deportivos")
Sector.create(name: "9313.- Actividades de los gimnasios")
Sector.create(name: "9319.- Otras actividades deportivas")
Sector.create(name: "9321.- Actividades de los parques de atracciones y los parques temáticos")
Sector.create(name: "9329.- Otras actividades recreativas y de entretenimiento")
Sector.create(name: "S.- OTROS SERVICIOS")
Sector.create(name: "9411.- Actividades de organizaciones empresariales y patronales")
Sector.create(name: "9412.- Actividades de organizaciones profesionales")
Sector.create(name: "9420.- Actividades sindicales")
Sector.create(name: "9491.- Actividades de organizaciones religiosas")
Sector.create(name: "9492.- Actividades de organizaciones políticas")
Sector.create(name: "9499.- Otras actividades asociativas n.c.o.p.")
Sector.create(name: "9511.- Reparación de ordenadores y equipos periféricos")
Sector.create(name: "9512.- Reparación de equipos de comunicación")
Sector.create(name: "9521.- Reparación de aparatos electrónicos de audio y vídeo de uso doméstico")
Sector.create(name: "9522.- Reparación de aparatos electrodomésticos y de equipos para el hogar y el jardín")
Sector.create(name: "9523.- Reparación de calzado y artículos de cuero")
Sector.create(name: "9524.- Reparación de muebles y artículos de menaje")
Sector.create(name: "9525.- Reparación de relojes y joyería")
Sector.create(name: "9529.- Reparación de otros efectos personales y artículos de uso doméstico")
Sector.create(name: "9601.- Lavado y limpieza de prendas textiles y de piel")
Sector.create(name: "9602.- Peluquería y otros tratamientos de belleza")
Sector.create(name: "9603.- Pompas fúnebres y actividades relacionadas")
Sector.create(name: "9604.- Actividades de mantenimiento físico")
Sector.create(name: "9609.- Otras servicios personales n.c.o.p.")
Sector.create(name: "T.- ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMÉSTICO; ACTIVIDADES DE LOS HOGARES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO")
Sector.create(name: "9700.- Actividades de los hogares como empleadores de personal doméstico")
Sector.create(name: "9810.- Actividades de los hogares como productores de bienes para uso propio")
Sector.create(name: "9820.- Actividades de los hogares como productores de servicios para uso propio")
Sector.create(name: "U.- ACTIVIDADES DE ORGANIZACIONES Y ORGANISMOS EXTRATERRITORIALES")
Sector.create(name: "9900.- Actividades de organizaciones y organismos extraterritoriales")
